### Trabajo practico 2

## Ejercicio 2

Se pretende estimar los valores de producción $Y$ (en miles de toneladas) en función del tiempo $X$ (en meses) con los datos:

| X  | Y   |
|----|-----|
| 4  | 11  |
| 7  | 80  |
| 12 | 140 |
| 15 | 336 |
| 21 | 450 |

Se plantea un modelo de la forma $Y = a + bx + cx^2$. Encontrar los estimadores de mínimos cuadrados para $a$, $b$ y $c$.

In [9]:
import numpy as np

x = np.array([4, 7, 12, 15, 21])
y = np.array([11, 80, 140, 336, 450])

### Formas matriciales
Asi evitamos estar derivando y solo multiplicaciones matriciales

In [10]:
X = np.column_stack([np.ones(len(x)), x, x**2])
XtX = X.T @ X
XtY = X.T @ y

print("Matriz de diseño X:")
print(X)
print()
print("XᵀX =")
print(XtX)
print()
print("XᵀY =")
print(XtY)

Matriz de diseño X:
[[  1.   4.  16.]
 [  1.   7.  49.]
 [  1.  12. 144.]
 [  1.  15. 225.]
 [  1.  21. 441.]]

XᵀX =
[[5.00000e+00 5.90000e+01 8.75000e+02]
 [5.90000e+01 8.75000e+02 1.47710e+04]
 [8.75000e+02 1.47710e+04 2.68499e+05]]

XᵀY =
[  1017.  16774. 298306.]


In [11]:
beta = np.linalg.solve(XtX, XtY)
a, b, c = beta

print(f"Estimadores de mínimos cuadrados:")
print(f"  a = {a:.6f}")
print(f"  b = {b:.6f}")
print(f"  c = {c:.6f}")
print()
print(f"Modelo ajustado: Y = {a:.4f} + ({b:.4f})x + ({c:.4f})x²")

y_hat = a + b*x + c*x**2
errores = y - y_hat

Estimadores de mínimos cuadrados:
  a = -71.419042
  b = 18.254575
  c = 0.339515

Modelo ajustado: Y = -71.4190 + (18.2546)x + (0.3395)x²


In [12]:
ss_res = np.sum(errores**2)
ss_tot = np.sum((y - np.mean(y))**2)
r2 = 1 - ss_res / ss_tot

print(f"{'x':>4} {'Y real':>8} {'Y ajustado':>12} {'Error':>10}")
print("-" * 40)
for xi, yi, yhi, ei in zip(x, y, y_hat, errores):
    print(f"{xi:>4} {yi:>8} {yhi:>12.4f} {ei:>10.4f}")
print()

# metrica sencilla
print(f"R² = {r2:.6f}")
print(f"Suma de cuadrados residual = {ss_res:.4f}")

   x   Y real   Y ajustado      Error
----------------------------------------
   4       11       7.0315     3.9685
   7       80      72.9992     7.0008
  12      140     196.5260   -56.5260
  15      336     278.7904    57.2096
  21      450     461.6530   -11.6530

R² = 0.950477
Suma de cuadrados residual = 6668.6782
